# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DYZB-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB-Swift
pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit', '~> 3.0.2'             
pod 'pop', '~> 1.0.9'
pod 'JHPullToRefreshKit', '~> 1.0.1'  
end